on:
  pull_request:
  push:
    branches:
      - main

name: continuous-integration

env:
  CLIPPY_OPTIONS: "-D warnings"

jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust toolchain and cache
        uses: actions-rust-lang/setup-rust-toolchain@v1.8.0
        with:
          rustflags: ""

      - name: Formatting
        run: cargo fmt --all -- --check

      - name: Clippy
        run: cargo clippy --workpace -- $CLIPPY_OPTIONS

      - name: Tests
        run: cargo test
