on:
  pull_request:
  push:
    branches:
      - main

name: continuous-integration

jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust toolchain and cache
        uses: actions-rust-lang/setup-rust-toolchain@v1.8.0
        with:
          rustflags: ""

      - name: Formatting
        run: make fmt-check

      - name: Clippy
        run: make clippy

      - name: Tests
        run: make test
